AllCops:
  Exclude:
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - 'Gemfile*'

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false
